feat: main-service
Volk0vArtem/java-explore-with-me pull request #2
Opened 2024-08-21 16:19 UTC by Volk0vArtem

2024-08-22 20:51 UTC, andrew-larkin requested changes
Привет! Очень хорошо, остается внести несколько правок и можно будет двигаться дальше.

2024-08-22 20:51 UTC, andrew-larkin commented on docker-compose.yml
>      container_name: stats-service-container
для сервисов стоит также добавить настройку restart on failure

2024-08-22 20:51 UTC, andrew-larkin commented on main-service/src/main/java/ru/practicum/admin/events/model/UpdateEventAdminRequest.java
> +    private Location location;
для location нужен отдельный dto. везде где в dto встречается такая запись, нужно заменить на locationDto

2024-08-22 20:51 UTC, andrew-larkin commented on main-service/src/main/java/ru/practicum/users/events/model/Location.java
> +public class Location {
location, по идее, должна сохраняться в БД как отдельная сущность

2024-08-22 21:54 UTC, Volk0vArtem commented on main-service/src/main/java/ru/practicum/admin/events/model/UpdateEventAdminRequest.java
> +    private Location location;
Привет! В спецификации во всех реквестах и респонсах это поле именно Location называется, так что если менять на LocationDto просто тесты не будут проходить

2024-08-22 21:55 UTC, Volk0vArtem commented on main-service/src/main/java/ru/practicum/users/events/model/Location.java
> +public class Location {
Судя по тому, что в спецификации даже dto для Location не предусмотрели, думаю, что не подразумевалось, что под неё надо делать отдельную таблицу, тем более как-будто там почти все связи будут one-to-one.
Но если ты уверен что стоит сделать отдельную сущность то сделаю 🙃

2024-08-23 15:06 UTC, andrew-larkin approved these changes
Привет! Отлично, работа принята!

2024-08-23 16:00 UTC, merged